eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
   #启动服务注册
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka1